CREATE TABLE owl(
 id SERIAL PRIMARY KEY,
 strategy INT NOT NULL,
 players SMALLINT NOT NULL,
 owls SMALLINT NOT NULL,
 actions SMALLINT NOT NULL,
 suns SMALLINT NOT NULL,
 won BOOL NOT NULL,
 elapsed DOUBLE PRECISION NOT NULL
);